[marketplaces.openai-bundled]
source_type = "local"
source = "/home/rileyschuit/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
source_type = "local"
source = "/home/rileyschuit/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[marketplaces.ecc]
source_type = "git"
source = "https://github.com/affaan-m/ECC.git"

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."ecc@ecc"]
enabled = true

[mcp_servers.node_repl]
args = []
command = "/usr/lib/chatgpt/resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/usr/lib/chatgpt/resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/usr/lib/chatgpt/resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/home/rileyschuit/.codex:/usr/lib/chatgpt/resources/cua_node/lib/node_modules"
CODEX_HOME = "/home/rileyschuit/.codex"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_TINYSKY_ENABLED = "0"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.825.51511"
NODE_REPL_TRUSTED_SERVICES = '{"browser":"/home/rileyschuit/.codex/plugins/cache/openai-bundled/browser/26.825.51511/scripts/browser-service.mjs"}'
CODEX_CLI_PATH = "/usr/lib/chatgpt/resources/codex"

[mcp_servers.cua_repl]
command = "/usr/lib/chatgpt/ChatGPT"
enabled = false

[projects."/home/rileyschuit/Documents/Codex/2026-09-09/use-only-the-slack-connector-for"]
trust_level = "trusted"

[projects."/home/rileyschuit"]
trust_level = "trusted"

[desktop]
conversationDetailMode = "STEPS_PROSE"
sansFontSize = 14
codeFontSize = 13
ambient-suggestions-enabled = true
followUpQueueMode = "queue"

[features]
hooks = true

[hooks.state]

[hooks.state."/home/rileyschuit/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:754dc89ea98d288e1cd184954588e5e76a696ab679d2e2d459d2d7acd7321779"
